"""add_warm_start_tables

Revision ID: e4f17b18e062
Revises: 
Create Date: 2025-12-11 17:05:19.922413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4f17b18e062'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coordi_images', 'image_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('coordi_images', 'is_main',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='대표 썸네일 여부',
               existing_server_default=sa.text('false'))
    op.alter_column('coordi_images', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_table_comment(
        'coordi_items',
        existing_comment='코디와 아이템의 N:M 관계 테이블',
        schema=None
    )
    op.alter_column('coordis', 'coordi_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('coordis', 'season',
               existing_type=sa.TEXT(),
               type_=sa.Enum('spring', 'summer', 'fall', 'winter', name='coordi_season_enum'),
               comment=None,
               existing_comment='4계절 (필터링용)',
               existing_nullable=True)
    op.alter_column('coordis', 'style',
               existing_type=sa.TEXT(),
               type_=sa.Enum('casual', 'street', 'sporty', 'minimal', name='coordi_style_enum'),
               comment=None,
               existing_comment='코디 무드/스타일',
               existing_nullable=True)
    op.alter_column('coordis', 'gender',
               existing_type=sa.TEXT(),
               type_=sa.Enum('male', 'female', name='coordi_gender_enum'),
               existing_comment='코디 대상 성별',
               existing_nullable=True)
    op.alter_column('coordis', 'description_embedding',
               existing_type=sa.NullType(),
               comment='Description embedding vector for semantic search (512 dimensions)',
               existing_comment='의미 검색을 위한 Description 임베딩 벡터(512차원)',
               existing_nullable=True)
    op.alter_column('coordis', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_coordis_embedding', table_name='coordis', postgresql_ops={'description_embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('fitting_result_images', 'image_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('fitting_result_images', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_table_comment(
        'fitting_result_items',
        existing_comment='가상 피팅 결과와 아이템의 N:M 관계 테이블',
        schema=None
    )
    op.alter_column('fitting_results', 'fitting_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('fitting_results', 'status',
               existing_type=sa.TEXT(),
               type_=sa.Enum('processing', 'completed', 'failed', 'timeout', name='fitting_result_status_enum'),
               nullable=False,
               existing_comment='피팅 작업 상태',
               existing_server_default=sa.text("'processing'::text"))
    op.alter_column('fitting_results', 'current_step',
               existing_type=sa.TEXT(),
               type_=sa.Enum('top', 'bottom', 'outer', name='fitting_step_enum'),
               existing_comment='현재 처리 단계 (processing 상태일 때)',
               existing_nullable=True)
    op.alter_column('fitting_results', 'failed_step',
               existing_type=sa.TEXT(),
               type_=sa.Enum('top', 'bottom', 'outer', name='fitting_step_enum'),
               existing_comment='실패한 단계 (failed 상태일 때)',
               existing_nullable=True)
    op.alter_column('fitting_results', 'finished_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='작업 완료/실패/타임아웃 시점 (status가 completed/failed/timeout일 때)',
               existing_nullable=True)
    op.alter_column('fitting_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('item_images', 'image_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('item_images', 'is_main',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='대표 썸네일 여부',
               existing_server_default=sa.text('false'))
    op.alter_column('item_images', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('items', 'item_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('items', 'category',
               existing_type=sa.TEXT(),
               type_=sa.Enum('top', 'bottom', 'outer', name='item_category_enum'),
               existing_nullable=False)
    op.alter_column('items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tags', 'tag_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_closet_items', 'added_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_table_comment(
        'user_closet_items',
        existing_comment='사용자와 아이템의 N:M 관계 테이블 (옷장)',
        schema=None
    )
    op.add_column('user_coordi_interactions', sa.Column('is_trained', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('user_coordi_interactions', 'action_type',
               existing_type=sa.TEXT(),
               type_=sa.Enum('like', 'skip', 'preference', name='coordi_action_enum'),
               existing_nullable=False)
    op.alter_column('user_coordi_interactions', 'interacted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_table_comment(
        'user_coordi_interactions',
        existing_comment='사용자와 코디의 N:M 관계 테이블 (스와이프 이력)',
        schema=None
    )
    op.alter_column('user_coordi_view_logs', 'log_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_coordi_view_logs', 'view_started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='조회 시작 시간',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_images', 'image_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_images', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_preferred_tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_table_comment(
        'user_preferred_tags',
        existing_comment='사용자와 선호 태그의 N:M 관계 테이블',
        schema=None
    )
    op.alter_column('users', 'user_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'gender',
               existing_type=sa.TEXT(),
               type_=sa.Enum('male', 'female', name='user_gender_enum'),
               existing_comment='사용자 성별',
               existing_nullable=True)
    op.alter_column('users', 'has_completed_onboarding',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='온보딩(선호도 설정) 완료 여부',
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'has_completed_onboarding',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='온보딩(선호도 설정) 완료 여부',
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'gender',
               existing_type=sa.Enum('male', 'female', name='user_gender_enum'),
               type_=sa.TEXT(),
               existing_comment='사용자 성별',
               existing_nullable=True)
    op.alter_column('users', 'user_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'user_preferred_tags',
        '사용자와 선호 태그의 N:M 관계 테이블',
        existing_comment=None,
        schema=None
    )
    op.alter_column('user_preferred_tags', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_images', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_images', 'image_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_coordi_view_logs', 'view_started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='조회 시작 시간',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_coordi_view_logs', 'log_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'user_coordi_interactions',
        '사용자와 코디의 N:M 관계 테이블 (스와이프 이력)',
        existing_comment=None,
        schema=None
    )
    op.alter_column('user_coordi_interactions', 'interacted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_coordi_interactions', 'action_type',
               existing_type=sa.Enum('like', 'skip', 'preference', name='coordi_action_enum'),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('user_coordi_interactions', 'is_trained')
    op.create_table_comment(
        'user_closet_items',
        '사용자와 아이템의 N:M 관계 테이블 (옷장)',
        existing_comment=None,
        schema=None
    )
    op.alter_column('user_closet_items', 'added_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tags', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tags', 'tag_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('items', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('items', 'category',
               existing_type=sa.Enum('top', 'bottom', 'outer', name='item_category_enum'),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('items', 'item_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('item_images', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('item_images', 'is_main',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='대표 썸네일 여부',
               existing_server_default=sa.text('false'))
    op.alter_column('item_images', 'image_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('fitting_results', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('fitting_results', 'finished_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='작업 완료/실패/타임아웃 시점 (status가 completed/failed/timeout일 때)',
               existing_nullable=True)
    op.alter_column('fitting_results', 'failed_step',
               existing_type=sa.Enum('top', 'bottom', 'outer', name='fitting_step_enum'),
               type_=sa.TEXT(),
               existing_comment='실패한 단계 (failed 상태일 때)',
               existing_nullable=True)
    op.alter_column('fitting_results', 'current_step',
               existing_type=sa.Enum('top', 'bottom', 'outer', name='fitting_step_enum'),
               type_=sa.TEXT(),
               existing_comment='현재 처리 단계 (processing 상태일 때)',
               existing_nullable=True)
    op.alter_column('fitting_results', 'status',
               existing_type=sa.Enum('processing', 'completed', 'failed', 'timeout', name='fitting_result_status_enum'),
               type_=sa.TEXT(),
               nullable=True,
               existing_comment='피팅 작업 상태',
               existing_server_default=sa.text("'processing'::text"))
    op.alter_column('fitting_results', 'fitting_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'fitting_result_items',
        '가상 피팅 결과와 아이템의 N:M 관계 테이블',
        existing_comment=None,
        schema=None
    )
    op.alter_column('fitting_result_images', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('fitting_result_images', 'image_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.create_index('idx_coordis_embedding', 'coordis', ['description_embedding'], unique=False, postgresql_ops={'description_embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('coordis', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('coordis', 'description_embedding',
               existing_type=sa.NullType(),
               comment='의미 검색을 위한 Description 임베딩 벡터(512차원)',
               existing_comment='Description embedding vector for semantic search (512 dimensions)',
               existing_nullable=True)
    op.alter_column('coordis', 'gender',
               existing_type=sa.Enum('male', 'female', name='coordi_gender_enum'),
               type_=sa.TEXT(),
               existing_comment='코디 대상 성별',
               existing_nullable=True)
    op.alter_column('coordis', 'style',
               existing_type=sa.Enum('casual', 'street', 'sporty', 'minimal', name='coordi_style_enum'),
               type_=sa.TEXT(),
               comment='코디 무드/스타일',
               existing_nullable=True)
    op.alter_column('coordis', 'season',
               existing_type=sa.Enum('spring', 'summer', 'fall', 'winter', name='coordi_season_enum'),
               type_=sa.TEXT(),
               comment='4계절 (필터링용)',
               existing_nullable=True)
    op.alter_column('coordis', 'coordi_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'coordi_items',
        '코디와 아이템의 N:M 관계 테이블',
        existing_comment=None,
        schema=None
    )
    op.alter_column('coordi_images', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('coordi_images', 'is_main',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='대표 썸네일 여부',
               existing_server_default=sa.text('false'))
    op.alter_column('coordi_images', 'image_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
